# Qwen-MoE Configuration
# Centralized configuration for all components

# GPU Configuration
gpu:
  cuda_visible_devices: "3"  # GPU device to use
  device: "cuda:0"  # Device string for PyTorch

# Model Configuration
model:
  base_model: "Qwen/Qwen3-4B-Instruct-2507"
  max_length: 512
  trust_remote_code: true
  generation:
    temperature: null
    top_p: null
    max_new_tokens: 100
    do_sample: false
    pad_token_id: null
    eos_token_id: null

# LoRA Configuration
lora:
  r: 64
  alpha: 128
  dropout: 0.1
  target_modules: ["gate_proj", "up_proj", "down_proj"]
  bias: "none"

# Training Configuration
training:
  epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  fp16: true
  max_grad_norm: 1.0
  logging_steps: 10
  save_steps: 500
  save_total_limit: 2
  evaluation_strategy: "steps"
  eval_steps: 500
  load_best_model_at_end: true

# Data Configuration
data:
  max_samples: null  # null means use all samples
  eval_max_samples: 1000  # Maximum samples for evaluation

# Output Configuration
output:
  domain_models_dir: "domain_models"
  experiments_dir: "experiments"
  logs_dir: "logs"

# Domain-specific configurations
domains:
  medical:
    max_length: 512
    num_choices: 4
  law:
    max_length: 512
    num_choices: 5
  math:
    max_length: 1024
    num_choices: 5
  code:
    max_length: 1024
    num_choices: 1
